apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dannylwe/go-simple-app'
    targetRevision: main
    path: deploy/helm/argocd/applications/monitoring
    # helm:
    #   valueFiles:
    #     - prometheus.yaml
    #     - loki.yaml
    #     - promtail.yaml
    #     - tempo.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
