apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: simple-app-port
    port: 80
    protocol: TCP
    targetPort: 9002
  selector:
    app: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
