appName: go-simple-app
# host: go-simple.192.168.105.2.sslip.io #ip is got from minikube ip
host: go-simple.172.24.0.4.sslip.io #ip is got from minikube ip
ingressName: go-simple-ingress
namespace: default
appPort: 9002
servicePort: 80
replicas: 1
image:
  name: acehanks/go-simple-app
  tag: v3